use_frameworks!

platform :ios, '9.0'

target 'TestDemo_Example' do
  pod 'TestDemo', :path => '../'
   #pod 'TestDemo', :podspec => '../TestDemo.podspec'

  target 'TestDemo_Tests' do
    inherit! :search_paths

    
  end
end
